# Site settings
title: Muhammad Awais Malik
twitter_username: owaismalik_1
name: Muhammad Awais Malik

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Linkedin
   url: https://www.linkedin.com/in/immuhammadawais/
 - title: GitHub
   url: https://github.com/awaismk
   
#Any buzzword skills you want to include
skills:
 - Linux
 - AWS
 - DevOps (Git, Docker, Kubernetes, Jenkins, Ansible, Terraform)
 - Microservices
 - SQL
 - REST
 - Windows Server Administration
 - Technical Support

#Work experience is required
roles:
 - title: DevOps/Cloud Operations Engineer
   start: 2018
   end: Ongoing
   employer: Crossover
   description: Administering and managing Linux and Windows based Servers for various software products. <br/> Managing Cloud platforms (AWS, Azure) for users and assigning use-case policies. <br/> Providing IT Operations support and solving infrastructure and IT access issues. <br/> Monitoring products actively using Nagios, Zabbix, Kibana and taking quick actions through PagerDuty. <br/> Using DevOps tools Docker, Kubernetes, Ansible, Jenkins, Git for CICD operations. <br/> Providing infrastructure support and solving customer tickets related to product infrastructure issues.
 - title: Network Engineer
   start: 2016
   end: 2018
   employer: Nayatel
   description: Configuration and Troubleshooting of Company's WAN infrastructure issues including PPPOE and IPOE, as well as VPN internet services. <br/> Understanding of OSPF, BGP, ISIS, MPLS protocols, Providing Support for Multicast Channels and IPOE TV programs using IGMP, Providing technical support for level II Complaints of Access Layer. <br/> Installation and Configurations of new customers as per assigned plan. <br/> Testing of any new core related package and equipment. <br/> Strong hands-on experience implementing and troubleshooting Cisco networking equipment, protocols, and features e.g. Cisco and Juniper routers, Firewalls, routers, switches, LAN/WLAN issues. <br/> Knowledge and troubleshooting of Customer LAN side issues, as well as Company end problems including Optical issues as well as Core ring Traffic issues.
 - title: Junior Network Admin
   start: 2015
   end: 2016
   employer: Techno Ed Pvt Ltd.
   description: Installing, configuring, maintaining and upgrading corporate office's networks and in house servers, Updating company routers and switches for Certification labs, and integrating new server hardware and applications.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2015
   subject: Telecom Engineering (Networks and Digital Communications)
   school: COMSATS University Islamabad
   cgpa: 3.6 (Bronze Medalist)
   
#List of Certifications
Certifications:
 - <strong>CCNA</strong> (Cisco)
 - <strong>DevOps Essentials</strong> (LinuxAcademy)
 - <strong>Kubernetes Essentials</strong> (LinuxAcademy)
 - <strong>DevOps Beginner to Pro</strong> (Dice Analytics)

Intro: |
  I am an IT Engineer with DevOps and Technical Support as my field of experience and interest. I have fair knowledge of the essentials of working in organizations with my practical work experience of 5 years.<br/> 
  In a typical day of work, I deal with Customer requests, handle technical queries, and manage/monitor infrastructure. 
  With exceptional communication, listening and interpersonal skills, my self confidence, innovative approach and quick adaptability to changing processes and trends have been my biggest assets. 
  I am a quick learner and can relate to people from all walks of life. I value productivity and work with result-oriented techniques that ensure maximum throughput. 
  My workplace goal is to transit my enthusiasm and the ability to work within a team and promote the spirit of team work among the members.<br/><br/>
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
    <h4>Following points describe technical skill set attained during my professional career:</h4>
    <br/>1. Hands on DevOps Skills e.g. (Containerization: Docker), (Container Orchestration: Docker Swarm, Kubernetes), (Cloud Services: AWS( ECS, ECR, EC2, VPC, ELB, Route53, S3, EBS, IAM), Azure), (Platform: Docker & Linux), (IaC: Terraform), (Scripting: Python , Bash), (CI/CD: Jenkins), (Version Control: Git) 
    <br/>2. Strong knowledge of Microsoft, desktop and Mobile Internet support.
    <br/>3. Programming Skills in C, Java.
    <br/>4. Working knowledge of SQL, and practical implementation in Database administration.
    <br/>5. Front End Web Development skills and experience with HTML, CSS, JAVASCRIPT
    <br/>6. Advanced Manual and Automation software testing skills using Selenium.
    <br/>7. Management and Administration of Atlassian Tools (Jira, Confluence instances).
    <br/>8. Working on Production AWS instances, Docker containers, MSSQL/MySQL/ORACLE Databases on daily basis.
    <br/>9. Knowledge and troubleshooting of TCP/IP, LAN/WAN, DHCP Server, NAT, VPN.
    <br/>10. Working with Application protocols TELNET, FTP, HTTP, SMTP, POP3, SNMP, DNS, PING.
    <br/>11. Hands on Experience with Windows Server 2016, Sharepoint.
    <br/>12. Hands on work on Active Directory, DNS, DHCP, Hyper-V , IIS, Exchange.
    <br/>13. Experience on Microsoft Cloud Solution Azure, and hands on experience using AWS.
    <br/>14. Working experience with network protocols including ISIS, OSPF, MPLS etc.
